baseURL = "https://imperfectnetwork.ing/"
theme = "risotto"
title = "imperfect-networking"
author = "emdee"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
enableEmoji = true

# Automatically add content sections to main menu
# sectionPagesMenu = "main"

[params]
noindex = false

[params.theme]
palette = "tokyo-night-dark"

# Sidebar: about/bio
[params.about]
title = "> welcome"
description = "_a blog of frustration, anger, love, and passion._"
# logo = "🌙"

[[params.socialLinks]]
icon = "fa-brands fa-bluesky"
title = "Bluesky"
url = "https://bsky.app/profile/imperfectnetwork.ing"

[[params.socialLinks]]
icon = "fa-brands fa-youtube"
title = "YouTube"
url = "https://www.youtube.com/@emdee_"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "e-mail"
url = "mailto:iusedavpn@gmail.com"

[menu]
  # [[menu.main]]
  #   identifier = "placeholder"
  #   name = "nothing-here"
  #   url = "/placeholder/"
  #   pageRef = "/placeholder"
  #   weight = 30
 [[menu.main]]
   identifier = "personal"
   name = "personal-blogs"
   url = '/personal/'
   weight = 20
 [[menu.main]]
   identifier = "projects"
   name = "project-blogs"
   url = "/projects/"
   weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"



[markup]
  [markup.goldmark.renderer]
    unsafe = true
  # Table of contents
  # Add toc = true to content front matter to enable
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = true
  

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true